name: Suggest a Quest Change
description: Suggest an addition, amendment, or removal of a quest.
labels:
  - "Status: Triage"
  - "Suggestion"
  - "Quests"

body:
  - type: markdown
    attributes:
      value: |
        Use this form to suggest a **Quest Addition**, **Quest Amendment**, or **Quest Removal**.

        If your issue is game-breaking (e.g., quest cannot be completed, rewards not given, progression locked),
        please use the **Report Bug** template instead.

  - type: input
    id: title
    attributes:
      label: Title
      description: A short descriptive title for your quest suggestion.
      placeholder: "Example: Adjust EV Power Quest Requirements"
    validations:
      required: true

  - type: input
    id: discord
    attributes:
      label: Your GTNH Discord Username
      description: Leave empty if you don't have one, but this makes it easier to contact you if clarification is needed.
      placeholder: "Example: Fake"

  - type: input
    id: version
    attributes:
      label: Your Pack Version
      description: What version of the pack are you playing?
      placeholder: "Example: 2.5.1"
    validations:
      required: true

  - type: dropdown
    id: change_type
    attributes:
      label: Type of Quest Change
      description: Select the type of quest change you are suggesting.
      options:
        - Quest Addition
        - Quest Amendment
        - Quest Removal
    validations:
      required: true

  - type: input
    id: quest_name
    attributes:
      label: Quest Name
      description: The exact name of the quest.
      placeholder: "Example: Power Through EV"
    validations:
      required: true

  - type: input
    id: quest_id
    attributes:
      label: Quest ID (Optional)
      description: If known, provide the internal quest ID.
      placeholder: "Example: 12345"

  - type: textarea
    id: reality
    attributes:
      label: The Reality
      description: Describe the current state of the quest. What does it currently require or reward?
      placeholder: |
        Example:
        The quest currently requires 64 HV circuits and rewards 4 EV circuits.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Your Proposal
      description: What specific change are you proposing?
      placeholder: |
        Example:
        Reduce requirement to 32 HV circuits and adjust reward to 2 EV circuits.
    validations:
      required: true

  - type: checkboxes
    id: final
    attributes:
      label: Final Checklist
      description: Please confirm the following.
      options:
        - label: "I have searched the issue tracker and there is no similar quest suggestion already."
          required: true
        - label: "I understand this suggestion may not be implemented."
          required: true
        - label: "I understand this suggestion may be rejected based on community feedback."
          required: true
        - label: "I believe this change would improve the questing experience."
          required: true
